version: '3'
services:
  mongo-visualize-db:
    container_name: mongo-visualize-db
    image: mongo
    ports:
      - 27017:27017 #another yml file using 27017 port s triend using 27018 on localhost
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
    - ./mongo-visualizer-volume:/data/db
    - ./datasets:/tutorials

  mongo-data-express:
    container_name: mongo-data-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-visualize-db
      # - ME_CONFIG_MONGODB_PORT=27018 #this needs to be added as well, for above reason
    depends_on:
      - mongo-visualize-db
    volumes:
    - ./mongo-visualizer-volume:/data/db

volumes:
  mongo-data-volume:
    driver: local